import TopologyProject.Definitions.Points

structure QInterval where
  left : Rat
  right : Rat
  left_lt_right : left < right

def qIntervalLe (I J : QInterval) : Prop :=
  J.left ≤ I.left ∧ I.right ≤ J.right

instance : LE QInterval where
  le := qIntervalLe

def qIntervalPreorder : Preorder QInterval where
  le := qIntervalLe
  refl := by
    intro I
    constructor
    · exact Rat.le_refl
    · exact Rat.le_refl
  trans := by
    intro I J K hIJ hJK
    rcases hIJ with ⟨hJleft, hIright⟩
    rcases hJK with ⟨hKleft, hJright⟩
    constructor
    · calc
        K.left ≤ J.left := hKleft
        _ ≤ I.left := hJleft
    · calc
        I.right ≤ J.right := hIright
        _ ≤ K.right := hJright

def G1Family (I : QInterval) : Subset QInterval :=
  fun J => I.left < J.left ∧ J.right < I.right

def leftSplit (I : QInterval) (c : Rat) (h : I.left < c) : QInterval :=
  ⟨I.left, c, h⟩

def rightSplit (I : QInterval) (d : Rat) (h : d < I.right) : QInterval :=
  ⟨d, I.right, h⟩

def G2Family (I : QInterval) (d c : Rat)
    (hAc : I.left < c) (hDb : d < I.right) : Subset QInterval :=
  fun J =>
    J = leftSplit I c hAc ∨
    J = rightSplit I d hDb

inductive realCover : QInterval → Subset QInterval → Prop
| refl {U : Subset QInterval} {I : QInterval} : U I → realCover I U
| trans {U V : Subset QInterval} {I : QInterval} :
    realCover I U → (U ◁ₛ[realCover] V) → realCover I V
| loc {U V : Subset QInterval} {I : QInterval} :
    realCover I U → realCover I V → realCover I (U↓[qIntervalPreorder] ∩ V↓[qIntervalPreorder])
| ext {I J : QInterval} : qIntervalPreorder.le I J → realCover I (singleton J)
| g1 (I : QInterval) : realCover I (G1Family I)
| g2 (I : QInterval) (d c : Rat)
  (hAd : I.left < d) (hDc : d < c) (hCb : c < I.right) :
  realCover I (G2Family I d c (show I.left < c from by
    calc
      I.left < d := hAd
      _ < c := hDc) (show d < I.right from by
    calc
      d < c := hDc
      _ < I.right := hCb))

/-
  Finitary cover relation generated by G2 only.
-/
inductive realCoverFin : QInterval → Subset QInterval → Prop
| refl {U : Subset QInterval} {I : QInterval} : U I → realCoverFin I U
| trans {U V : Subset QInterval} {I : QInterval} :
    realCoverFin I U → (U ◁ₛ[realCoverFin] V) → realCoverFin I V
| loc {U V : Subset QInterval} {I : QInterval} :
    realCoverFin I U → realCoverFin I V → realCoverFin I (U↓[qIntervalPreorder] ∩ V↓[qIntervalPreorder])
| ext {I J : QInterval} : qIntervalPreorder.le I J → realCoverFin I (singleton J)
| g2 (I : QInterval) (d c : Rat)
  (hAd : I.left < d) (hDc : d < c) (hCb : c < I.right) :
  realCoverFin I (G2Family I d c (show I.left < c from by
    calc
      I.left < d := hAd
      _ < c := hDc) (show d < I.right from by
    calc
      d < c := hDc
      _ < I.right := hCb))

def listSubset {X : Type} (U : Subset X) (l : List X) : Prop :=
  ∀ x, List.Mem x l → U x

def intervalCoveredByList (I : QInterval) (l : List QInterval) : Prop :=
  ∀ x : Rat, I.left < x → x < I.right →
    ∃ J, List.Mem J l ∧ J.left < x ∧ x < J.right

def subsetOfList (l : List QInterval) : Subset QInterval :=
  fun J => List.Mem J l

def finiteSubcoverData (I : QInterval) (U : Subset QInterval) : Prop :=
  ∃ l : List QInterval, listSubset U l ∧ intervalCoveredByList I l

noncomputable def realFormalTopology : FormalTopology QInterval where
  preorder := qIntervalPreorder
  cover := realCover
  refl := by
    intro U I hI
    exact realCover.refl hI
  trans := by
    intro U V I hIU hUV
    exact realCover.trans hIU hUV
  loc := by
    intro U V I hIU hIV
    exact realCover.loc hIU hIV
  ext := by
    intro I J hIJ
    exact realCover.ext hIJ

def offZeroBase : Subset QInterval :=
  fun I => 0 < I.left ∨ I.right < 0

def offZeroIntervals : Subset QInterval :=
  offZeroBase↓[qIntervalPreorder]

def reciprocalRel (u v : QInterval) : Prop :=
  offZeroIntervals u ∧
  v.left ≤ (1 / u.right) ∧
  (1 / u.left) ≤ v.right

def reciprocalPreimage (U : Subset QInterval) : Subset QInterval :=
  fun w => ∃ t, U t ∧ reciprocalRel w t

def PtR : Type := Subset QInterval

def pointLt (alpha beta : PtR) : Prop :=
  ∃ I, alpha I ∧ ∃ J, beta J ∧ I.right < J.left

def pointLe (alpha beta : PtR) : Prop :=
  ¬ pointLt beta alpha

def barOfRat (x : Rat) : PtR :=
  fun I => I.left < x ∧ x < I.right

def Cset (alpha beta : PtR) : Subset QInterval :=
  fun I => pointLt (barOfRat I.right) alpha ∨ pointLt beta (barOfRat I.left)

noncomputable def Ispace (alpha beta : PtR) : FormalTopology QInterval :=
  closedSubspaceTopology realFormalTopology (Cset alpha beta)

notation "I(" alpha "," beta ")" => Ispace alpha beta

def enclosesByRationals (alpha beta : PtR) (r s : Rat) : Prop :=
  pointLt (barOfRat r) alpha ∧ pointLt alpha beta ∧ pointLt beta (barOfRat s)

def intervalImageSubset (f : Rat → Rat) (I J : QInterval) : Prop :=
  ∀ x : Rat, I.left < x → x < I.right → J.left < f x ∧ f x < J.right

def Af (f : Rat → Rat) : QInterval → QInterval → Prop :=
  fun I J => intervalImageSubset f I J

def ptAf (f : Rat → Rat) : PtR → PtR :=
  PtMap realFormalTopology realFormalTopology (Af f)

/-
  Lebesgue-number formulation for a finite family of rational intervals.
-/
def intervalContains (I : QInterval) (x : Rat) : Prop :=
  I.left < x ∧ x < I.right

def unionOfIntervals (V0 : List QInterval) : Subset Rat :=
  fun x => ∃ I, List.Mem I V0 ∧ intervalContains I x

def pairInSomeInterval (V0 : List QInterval) (x y : Rat) : Prop :=
  ∃ I, List.Mem I V0 ∧ intervalContains I x ∧ intervalContains I y

def closeBy (δ x y : Rat) : Prop :=
  x < y + δ ∧ y < x + δ

def isIntervalSubsetRat (S : Subset Rat) : Prop :=
  ∀ x y z : Rat, S x → S y → x < z → z < y → S z
